import type { Metadata } from "next";
// Use the standard next/font/google module
import { Inter } from "next/font/google"; 
import "./globals.css";

// Configure the Inter font
const inter = Inter({ 
  subsets: ["latin"],
  display: "swap", 
  // We use .className directly below, so defining a variable is optional
}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the Inter font's className directly to the <body> tag */}
      <body className={`${inter.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}