-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.about_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying DEFAULT 'BULLMONEY'::character varying,
  subtitle character varying DEFAULT 'REAL TRADERS. REAL PROFITS.'::character varying,
  description_1 text,
  description_2 text,
  image_url text,
  stats jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT about_content_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admins (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id bigint NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL DEFAULT 'MODERATOR'::admin_role,
  permissions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admins_pkey PRIMARY KEY (id),
  CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.recruits(id)
);
CREATE TABLE public.affiliate_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  headline character varying DEFAULT 'Join VIP'::character varying,
  subheadline text DEFAULT 'Get access to premium trading setups and live sessions'::text,
  benefits jsonb DEFAULT '[]'::jsonb,
  cta_text character varying DEFAULT 'Get Started'::character varying,
  cta_url text DEFAULT 'https://t.me/bullmoney'::text,
  video_id character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_content_pkey PRIMARY KEY (id)
);
CREATE TABLE public.affiliate_earnings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  affiliate_id bigint,
  trader_id bigint,
  transaction_type text NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  lots_traded numeric,
  commission_rate numeric,
  broker text,
  tier_at_time text,
  bonus_type text,
  bonus_multiplier numeric,
  status text DEFAULT 'pending'::text,
  approved_at timestamp with time zone,
  approved_by text,
  paid_at timestamp with time zone,
  payment_method text,
  payment_reference text,
  payment_notes text,
  earning_period_start date,
  earning_period_end date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_earnings_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_earnings_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES public.recruits(id),
  CONSTRAINT affiliate_earnings_trader_id_fkey FOREIGN KEY (trader_id) REFERENCES public.recruits(id)
);
CREATE TABLE public.affiliate_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  affiliate_id bigint,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  payment_method text NOT NULL,
  payment_details jsonb,
  period_start date NOT NULL,
  period_end date NOT NULL,
  status text DEFAULT 'pending'::text,
  requested_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  completed_at timestamp with time zone,
  processed_by text,
  admin_notes text,
  transaction_id text,
  transaction_proof_url text,
  failure_reason text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_payouts_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES public.recruits(id)
);
CREATE TABLE public.affiliate_referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  affiliate_id bigint,
  trader_id bigint,
  referral_code_used text,
  broker text,
  mt5_account text,
  status text DEFAULT 'pending'::text,
  verified_at timestamp with time zone,
  first_trade_date timestamp with time zone,
  last_trade_date timestamp with time zone,
  total_lots_traded numeric DEFAULT 0.00,
  total_deposits numeric DEFAULT 0.00,
  total_commission_generated numeric DEFAULT 0.00,
  current_month_lots numeric DEFAULT 0.00,
  is_active boolean DEFAULT false,
  activity_score integer DEFAULT 0,
  referred_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_referrals_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_referrals_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES public.recruits(id),
  CONSTRAINT affiliate_referrals_trader_id_fkey FOREIGN KEY (trader_id) REFERENCES public.recruits(id)
);
CREATE TABLE public.affiliate_social_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  affiliate_id bigint,
  platform text NOT NULL,
  post_url text,
  post_screenshot_url text,
  post_type text,
  status text DEFAULT 'pending'::text,
  verified_at timestamp with time zone,
  verified_by text,
  rejection_reason text,
  views integer,
  likes integer,
  comments integer,
  shares integer,
  posted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_social_posts_pkey PRIMARY KEY (id),
  CONSTRAINT affiliate_social_posts_affiliate_id_fkey FOREIGN KEY (affiliate_id) REFERENCES public.recruits(id)
);
CREATE TABLE public.affiliate_tiers (
  id integer NOT NULL DEFAULT nextval('affiliate_tiers_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  min_traders integer NOT NULL,
  max_traders integer,
  commission_percent numeric NOT NULL,
  xm_rate_per_lot numeric NOT NULL,
  vantage_rate_per_lot numeric NOT NULL,
  bonus_multiplier numeric DEFAULT 1.00,
  perks ARRAY,
  color text DEFAULT '#3b82f6'::text,
  icon text DEFAULT 'target'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT affiliate_tiers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.analyses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  content text NOT NULL,
  market character varying DEFAULT 'forex'::character varying,
  direction character varying DEFAULT 'neutral'::character varying,
  pair character varying,
  entry_price numeric,
  target_price numeric,
  stop_loss numeric,
  image_url text,
  is_published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  author_id uuid,
  confidence_score integer DEFAULT 5 CHECK (confidence_score >= 1 AND confidence_score <= 10),
  content_type text DEFAULT 'deep_dive'::text CHECK (content_type = ANY (ARRAY['deep_dive'::text, 'market_pulse'::text, 'blog_post'::text, 'quick_take'::text, 'trade_idea'::text, 'educational'::text])),
  rich_content jsonb,
  chart_config jsonb,
  attachments jsonb DEFAULT '[]'::jsonb,
  tickers ARRAY DEFAULT ARRAY[]::text[],
  view_count integer DEFAULT 0,
  bull_score integer DEFAULT 0,
  is_pro_only boolean DEFAULT false,
  reaction_counts jsonb DEFAULT '{"bear": 0, "bull": 0, "save": 0}'::jsonb,
  comment_count integer DEFAULT 0,
  CONSTRAINT analyses_pkey PRIMARY KEY (id),
  CONSTRAINT analyses_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.analysis_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  analysis_id uuid NOT NULL,
  user_id uuid NOT NULL,
  parent_id uuid,
  content text NOT NULL,
  rich_content jsonb,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analysis_comments_pkey PRIMARY KEY (id),
  CONSTRAINT analysis_comments_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id),
  CONSTRAINT analysis_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT analysis_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.analysis_comments(id)
);
CREATE TABLE public.analysis_reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  analysis_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reaction_type text NOT NULL CHECK (reaction_type = ANY (ARRAY['bull'::text, 'bear'::text, 'save'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analysis_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT analysis_reactions_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id),
  CONSTRAINT analysis_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.back_in_stock_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  email text NOT NULL,
  product_id text NOT NULL,
  product_name text,
  variant_name text,
  notified boolean DEFAULT false,
  notified_at timestamp with time zone,
  CONSTRAINT back_in_stock_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bullmoney_vip (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  buy_url text,
  coming_soon boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  image_url text,
  plan_options jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT bullmoney_vip_pkey PRIMARY KEY (id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  slug character varying NOT NULL UNIQUE,
  description text,
  image_url text,
  parent_id uuid,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.copy_trades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  analysis_id uuid NOT NULL,
  user_id uuid NOT NULL,
  copied_at timestamp with time zone DEFAULT now(),
  entry_price numeric,
  exit_price numeric,
  outcome text DEFAULT 'pending'::text CHECK (outcome = ANY (ARRAY['pending'::text, 'win'::text, 'loss'::text, 'cancelled'::text])),
  CONSTRAINT copy_trades_pkey PRIMARY KEY (id),
  CONSTRAINT copy_trades_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id),
  CONSTRAINT copy_trades_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.crash_groups (
  id text NOT NULL,
  fingerprint text NOT NULL UNIQUE,
  first_seen timestamp with time zone NOT NULL DEFAULT now(),
  last_seen timestamp with time zone NOT NULL DEFAULT now(),
  occurrence_count integer DEFAULT 1,
  affected_sessions integer DEFAULT 1,
  affected_users integer DEFAULT 0,
  error_name text,
  error_message text,
  source_file text,
  source_line integer,
  component text,
  max_severity text DEFAULT 'low'::text,
  avg_fps_at_crash real,
  affected_devices jsonb DEFAULT '{}'::jsonb,
  affected_browsers jsonb DEFAULT '{}'::jsonb,
  affected_os jsonb DEFAULT '{}'::jsonb,
  affected_countries jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'investigating'::text, 'resolved'::text, 'wont_fix'::text, 'duplicate'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])),
  assigned_to text,
  resolution_notes text,
  resolved_at timestamp with time zone,
  tags ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crash_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crash_logs (
  id text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  event_type text NOT NULL,
  component text NOT NULL,
  action text,
  target text,
  metadata jsonb DEFAULT '{}'::jsonb,
  session_id text NOT NULL,
  user_agent text,
  url text,
  device_tier text,
  fps integer,
  error_message text,
  error_stack text,
  severity text DEFAULT 'medium'::text,
  source_file text,
  source_line integer,
  source_column integer,
  function_name text,
  parsed_stack jsonb DEFAULT '[]'::jsonb,
  fps_lag_data jsonb,
  device_fingerprint jsonb,
  network_info jsonb,
  user_context jsonb,
  performance_timeline jsonb,
  dom_state jsonb,
  crash_fingerprint text,
  crash_group_id text,
  frame_analysis jsonb,
  memory_state jsonb,
  component_profiles jsonb,
  network_state jsonb,
  user_journey jsonb,
  crash_prediction jsonb,
  recommendations jsonb DEFAULT '[]'::jsonb,
  browser_details jsonb,
  viewport_details jsonb,
  is_resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by text,
  resolution_notes text,
  CONSTRAINT crash_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crypto_payment_audit (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payment_id uuid NOT NULL,
  order_number character varying,
  previous_status character varying,
  new_status character varying,
  admin_email character varying,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crypto_payment_audit_pkey PRIMARY KEY (id),
  CONSTRAINT crypto_payment_audit_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.crypto_payments(id)
);
CREATE TABLE public.crypto_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_number character varying NOT NULL UNIQUE,
  tx_hash character varying NOT NULL,
  coin character varying NOT NULL,
  network character varying NOT NULL,
  wallet_address character varying NOT NULL,
  sender_wallet character varying,
  amount_usd numeric NOT NULL,
  amount_crypto numeric,
  locked_price numeric,
  actual_amount_crypto numeric,
  product_id uuid,
  variant_id uuid,
  product_name character varying NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  user_id bigint,
  guest_email character varying,
  status USER-DEFINED DEFAULT 'pending'::crypto_payment_status,
  confirmations integer DEFAULT 0,
  required_confirmations integer DEFAULT 12,
  blockchain_verified boolean DEFAULT false,
  amount_verified boolean DEFAULT false,
  verification_attempts integer DEFAULT 0,
  last_verified_at timestamp with time zone,
  verification_error text,
  order_id uuid,
  admin_notes text,
  admin_reviewed_by character varying,
  admin_reviewed_at timestamp with time zone,
  submitted_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  price_locked_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  refund_status character varying,
  refund_amount_usd numeric,
  refund_id uuid,
  tx_hash_hash character varying,
  guest_email_hash character varying,
  CONSTRAINT crypto_payments_pkey PRIMARY KEY (id),
  CONSTRAINT crypto_payments_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT crypto_payments_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.variants(id),
  CONSTRAINT crypto_payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.crypto_refunds (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payment_id uuid NOT NULL,
  order_number character varying NOT NULL,
  status USER-DEFINED DEFAULT 'requested'::crypto_refund_status,
  refund_amount_usd numeric NOT NULL,
  refund_amount_crypto numeric,
  original_amount_usd numeric NOT NULL,
  coin character varying NOT NULL,
  network character varying,
  customer_email character varying NOT NULL,
  customer_wallet character varying,
  reason text NOT NULL,
  refund_tx_hash character varying,
  refund_wallet_used character varying,
  reviewed_by character varying,
  review_notes text,
  denial_reason text,
  policy_check_passed boolean DEFAULT false,
  policy_check_details text,
  requested_at timestamp with time zone DEFAULT now(),
  reviewed_at timestamp with time zone,
  processed_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crypto_refunds_pkey PRIMARY KEY (id),
  CONSTRAINT crypto_refunds_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.crypto_payments(id)
);
CREATE TABLE public.daily_trading_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  stat_date date NOT NULL,
  total_trades integer DEFAULT 0,
  winning_trades integer DEFAULT 0,
  losing_trades integer DEFAULT 0,
  breakeven_trades integer DEFAULT 0,
  total_pnl numeric DEFAULT 0,
  total_wins_amount numeric DEFAULT 0,
  total_losses_amount numeric DEFAULT 0,
  win_rate numeric,
  profit_factor numeric,
  average_win numeric,
  average_loss numeric,
  current_win_streak integer DEFAULT 0,
  current_loss_streak integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_trading_stats_pkey PRIMARY KEY (id)
);
CREATE TABLE public.deploy_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deployment_id character varying,
  commit_message character varying,
  emails_sent integer DEFAULT 0,
  emails_failed integer DEFAULT 0,
  sent_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deploy_notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.discount_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code character varying NOT NULL UNIQUE,
  description text,
  discount_type character varying NOT NULL CHECK (discount_type::text = ANY (ARRAY['PERCENTAGE'::character varying, 'FIXED'::character varying]::text[])),
  discount_value numeric NOT NULL,
  min_order_amount numeric DEFAULT 0 CHECK (min_order_amount >= 0::numeric),
  max_uses integer CHECK (max_uses IS NULL OR max_uses > 0),
  current_uses integer DEFAULT 0 CHECK (current_uses >= 0),
  starts_at timestamp with time zone,
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discount_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_drip_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL,
  source character varying DEFAULT 'recruits'::character varying,
  recruit_id bigint,
  newsletter_subscriber_id uuid,
  campaign_name character varying DEFAULT 'store_reminder_30day'::character varying,
  email_sequence_number integer DEFAULT 0,
  total_emails_to_send integer DEFAULT 15,
  subscribed boolean DEFAULT true,
  started_at timestamp with time zone DEFAULT now(),
  last_email_sent_at timestamp with time zone,
  next_email_scheduled_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  total_sent integer DEFAULT 0,
  total_opened integer DEFAULT 0,
  total_clicked integer DEFAULT 0,
  last_opened_at timestamp with time zone,
  last_clicked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_drip_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT email_drip_campaigns_recruit_id_fkey FOREIGN KEY (recruit_id) REFERENCES public.recruits(id),
  CONSTRAINT email_drip_campaigns_newsletter_subscriber_id_fkey FOREIGN KEY (newsletter_subscriber_id) REFERENCES public.newsletter_subscribers(id)
);
CREATE TABLE public.email_drip_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  email character varying NOT NULL,
  sequence_number integer NOT NULL,
  subject character varying NOT NULL,
  template_name character varying,
  status character varying DEFAULT 'pending'::character varying,
  resend_message_id character varying,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  opened_at timestamp with time zone,
  clicked_at timestamp with time zone,
  bounced_at timestamp with time zone,
  bounce_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_drip_history_pkey PRIMARY KEY (id),
  CONSTRAINT email_drip_history_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.email_drip_campaigns(id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  subject character varying NOT NULL,
  hero_title text NOT NULL DEFAULT ''::text,
  hero_subtitle text DEFAULT ''::text,
  hero_icon character varying DEFAULT 'check'::character varying,
  content_blocks jsonb DEFAULT '[]'::jsonb,
  primary_cta_text character varying DEFAULT ''::character varying,
  primary_cta_url character varying DEFAULT ''::character varying,
  secondary_cta_text character varying DEFAULT ''::character varying,
  secondary_cta_url character varying DEFAULT ''::character varying,
  footer_text text DEFAULT ''::text,
  promo_code character varying DEFAULT ''::character varying,
  promo_description text DEFAULT ''::text,
  attachments jsonb DEFAULT '[]'::jsonb,
  category character varying DEFAULT 'general'::character varying,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  send_type character varying DEFAULT 'manual'::character varying,
  interval_days integer DEFAULT 0,
  interval_hours integer DEFAULT 0,
  send_hour integer DEFAULT 9,
  send_minute integer DEFAULT 0,
  send_days_of_week jsonb DEFAULT '[]'::jsonb,
  target_audience character varying DEFAULT 'all'::character varying,
  drip_sequence_number integer DEFAULT 0,
  drip_days_after_signup integer DEFAULT 0,
  last_sent_at timestamp with time zone,
  next_scheduled_at timestamp with time zone,
  total_sent integer DEFAULT 0,
  total_opened integer DEFAULT 0,
  total_clicked integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  styles jsonb DEFAULT '{"hero": {"iconBg": "linear-gradient(135deg, #3b82f6, #1d4ed8)", "iconSize": "64px", "iconRadius": "50%"}, "mode": "dark", "colors": {"link": "#3b82f6", "error": "#ef4444", "border": "#222222", "cardBg": "#111111", "primary": "#3b82f6", "success": "#10b981", "textDim": "#666666", "warning": "#f59e0b", "cardBgAlt": "#0a0a0a", "textMuted": "#888888", "background": "#000000", "primaryDark": "#1d4ed8", "textPrimary": "#ffffff", "textSecondary": "#e0e0e0"}, "layout": {"columns": 2, "gridGap": "8px", "maxWidth": "600px"}, "borders": {"width": "1px", "radius": "16px", "radiusTiny": "8px", "radiusSmall": "12px"}, "buttons": {"primaryBg": "linear-gradient(135deg, #3b82f6, #1d4ed8)", "primaryText": "#ffffff", "secondaryBg": "transparent", "primaryRadius": "12px", "secondaryText": "#3b82f6", "primaryPadding": "18px 48px", "secondaryBorder": "#3b82f6"}, "spacing": {"elementGap": "16px", "sectionGap": "24px", "cardPadding": "24px", "containerPadding": "40px"}, "darkMode": {"cardBg": "#111111", "background": "#000000", "textPrimary": "#ffffff", "textSecondary": "#e0e0e0"}, "lightMode": {"cardBg": "#f8f9fa", "background": "#ffffff", "textPrimary": "#1a1a1a", "textSecondary": "#4a4a4a"}, "typography": {"bodySize": "16px", "heroSize": "32px", "tinySize": "12px", "smallSize": "14px", "fontFamily": "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif", "lineHeight": "1.7", "headingSize": "18px"}}'::jsonb,
  description text,
  html_body text,
  available_variables ARRAY DEFAULT '{}'::text[],
  send_to_admin boolean DEFAULT false,
  admin_only boolean DEFAULT false,
  last_edited_by character varying,
  CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.faq_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT faq_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.faq_content (
  id text NOT NULL DEFAULT 'main'::text,
  content jsonb NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT faq_content_pkey PRIMARY KEY (id)
);
CREATE TABLE public.faq_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid,
  question text NOT NULL,
  answer text NOT NULL,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT faq_items_pkey PRIMARY KEY (id),
  CONSTRAINT faq_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.faq_categories(id)
);
CREATE TABLE public.fps_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  component text,
  current_fps integer NOT NULL,
  target_fps integer DEFAULT 60,
  average_fps real,
  min_fps integer,
  max_fps integer,
  jank_count integer DEFAULT 0,
  dropped_frames integer DEFAULT 0,
  fps_stability real,
  avg_frame_time real,
  max_frame_time real,
  script_time real,
  layout_time real,
  paint_time real,
  memory_used_mb real,
  memory_percent real,
  memory_growth_rate real,
  device_model text,
  device_type text,
  gpu_tier text,
  cpu_cores integer,
  performance_score integer,
  browser text,
  browser_version text,
  os text,
  os_version text,
  dom_nodes integer,
  animating_elements integer,
  canvas_count integer,
  network_type text,
  network_latency integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fps_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gallery_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying,
  description text,
  media_url text NOT NULL,
  media_type character varying DEFAULT 'image'::character varying,
  thumbnail_url text,
  category character varying,
  is_featured boolean DEFAULT false,
  is_visible boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gallery_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gift_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  code text NOT NULL UNIQUE,
  amount numeric NOT NULL,
  balance numeric NOT NULL,
  recipient_email text NOT NULL,
  recipient_name text,
  sender_name text,
  sender_email text,
  message text,
  is_active boolean DEFAULT true,
  redeemed_at timestamp with time zone,
  redeemed_by text,
  expires_at timestamp with time zone DEFAULT (now() + '2 years'::interval),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT gift_cards_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hero_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  badge character varying,
  title character varying,
  subtitle text,
  primary_cta_label character varying,
  secondary_cta_label character varying,
  featured_title character varying,
  featured_subtitle text,
  featured_price_label character varying,
  featured_tag_label character varying,
  featured_note text,
  featured_image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hero_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hero_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  headline character varying DEFAULT 'BullMoney'::character varying,
  subheadline text DEFAULT 'Elite Trading Community & Premium Trading Setups'::text,
  button_text character varying DEFAULT 'View Trading Setups'::character varying,
  button_url character varying DEFAULT '#products'::character varying,
  hero_images ARRAY DEFAULT ARRAY[]::text[],
  beam_text_1 character varying DEFAULT 'Community'::character varying,
  beam_text_2 character varying DEFAULT 'Trading'::character varying,
  beam_text_3 character varying DEFAULT 'Setups'::character varying,
  show_spline boolean DEFAULT true,
  spline_url text DEFAULT 'https://prod.spline.design/your-scene-id/scene.splinecode'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hero_content_pkey PRIMARY KEY (id)
);
CREATE TABLE public.livestream_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  channel_url character varying,
  current_video_id character varying,
  is_live_now boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT livestream_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.livestream_videos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  youtube_id character varying NOT NULL,
  is_live boolean DEFAULT false,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT livestream_videos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.main_hero (
  id boolean NOT NULL DEFAULT true CHECK (id),
  title text,
  flip_list_1 text,
  flip_list_2 text,
  flip_list_3 text,
  slides jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT main_hero_pkey PRIMARY KEY (id)
);
CREATE TABLE public.navbar_modals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  modal_key character varying NOT NULL UNIQUE,
  label character varying NOT NULL,
  icon_name character varying,
  is_visible boolean DEFAULT true,
  is_highlighted boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT navbar_modals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.newsletter_messages_config (
  id text NOT NULL DEFAULT 'default'::text CHECK (id = 'default'::text),
  existing_subscriber_message text NOT NULL DEFAULT 'You''re already part of the family! 🐂 Check your inbox — we just sent you some goodies.'::text,
  existing_recruit_message text NOT NULL DEFAULT 'Welcome back, {firstName}! Your recruit + newsletter benefits are now active. Check your Gmail for exclusive insights.'::text,
  new_subscriber_message text NOT NULL DEFAULT 'Welcome to Bullmoney Gmail Intel! Check your Gmail for exclusive trading insights and your bonus guide.'::text,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by text,
  CONSTRAINT newsletter_messages_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.newsletter_subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  source character varying DEFAULT 'store_footer'::character varying,
  subscribed boolean DEFAULT true,
  subscribed_at timestamp with time zone DEFAULT now(),
  unsubscribed_at timestamp with time zone,
  resubscribed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  preferences jsonb DEFAULT '{"updates": true, "marketing": true}'::jsonb,
  tags ARRAY DEFAULT '{}'::text[],
  last_email_sent_at timestamp with time zone,
  total_emails_sent integer DEFAULT 0,
  admin_notes text,
  is_vip boolean DEFAULT false,
  CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  body text NOT NULL,
  channel text DEFAULT 'trades'::text,
  image_url text,
  action_url text,
  sent_count integer DEFAULT 0,
  failed_count integer DEFAULT 0,
  sent_by text,
  trigger_type text DEFAULT 'manual'::text,
  telegram_message_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  product_id uuid,
  variant_id uuid,
  product_snapshot jsonb NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.variants(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_number character varying NOT NULL UNIQUE,
  user_id bigint,
  guest_email character varying CHECK (guest_email IS NULL OR guest_email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  status USER-DEFINED DEFAULT 'PENDING'::order_status,
  shipping_address jsonb NOT NULL CHECK (jsonb_typeof(shipping_address) = 'object'::text),
  billing_address jsonb CHECK (billing_address IS NULL OR jsonb_typeof(billing_address) = 'object'::text),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  shipping_cost numeric DEFAULT 0 CHECK (shipping_cost >= 0::numeric),
  tax_amount numeric DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  total numeric NOT NULL CHECK (total >= 0::numeric),
  stripe_payment_intent_id character varying,
  stripe_charge_id character varying,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'::text),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.recruits(id)
);
CREATE TABLE public.panel_buttons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  button_key character varying NOT NULL UNIQUE,
  label character varying NOT NULL,
  icon_name character varying,
  action_type character varying DEFAULT 'modal'::character varying,
  action_target text,
  is_visible boolean DEFAULT true,
  is_admin_only boolean DEFAULT false,
  display_order integer DEFAULT 0,
  color character varying DEFAULT '#3b82f6'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT panel_buttons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.performance_metrics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  session_id text NOT NULL,
  component text NOT NULL,
  avg_fps real,
  min_fps real,
  max_fps real,
  render_count integer DEFAULT 0,
  avg_render_time real,
  device_tier text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT performance_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.price_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  analysis_id uuid,
  symbol text NOT NULL,
  target_price numeric NOT NULL,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['above'::text, 'below'::text])),
  is_triggered boolean DEFAULT false,
  triggered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT price_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT price_alerts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT price_alerts_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id)
);
CREATE TABLE public.product_categories (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  description text,
  icon_name character varying,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT product_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  url text NOT NULL,
  alt_text character varying,
  sort_order integer DEFAULT 0,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_images_pkey PRIMARY KEY (id),
  CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_media (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  media_type character varying NOT NULL CHECK (media_type::text = ANY (ARRAY['image'::character varying, 'video'::character varying]::text[])),
  url text NOT NULL,
  thumbnail_url text,
  alt_text character varying,
  title character varying,
  duration_seconds integer,
  width integer,
  height integer,
  file_size_bytes bigint,
  mime_type character varying,
  sort_order integer DEFAULT 0,
  is_primary boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_media_pkey PRIMARY KEY (id),
  CONSTRAINT product_media_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  short_description character varying,
  base_price numeric NOT NULL CHECK (base_price >= 0::numeric),
  compare_at_price numeric CHECK (compare_at_price >= 0::numeric),
  category_id uuid,
  status USER-DEFINED DEFAULT 'DRAFT'::product_status,
  featured boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  details jsonb DEFAULT '{}'::jsonb,
  seo_title character varying,
  seo_description character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  buy_url text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.profiles (
  id bigint NOT NULL,
  email character varying NOT NULL CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  full_name character varying,
  phone character varying,
  avatar_url text,
  saved_addresses jsonb DEFAULT '[]'::jsonb CHECK (jsonb_typeof(saved_addresses) = 'array'::text),
  preferences jsonb DEFAULT '{}'::jsonb CHECK (jsonb_typeof(preferences) = 'object'::text),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES public.recruits(id)
);
CREATE TABLE public.prop_firm_partners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  logo_url text,
  website_url text NOT NULL,
  affiliate_url text,
  partner_code character varying,
  discount_percent integer DEFAULT 0,
  tagline character varying,
  is_featured boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT prop_firm_partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.push_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recruit_id bigint,
  recruit_email text,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  device_type text,
  browser text,
  is_active boolean DEFAULT true,
  channel_trades boolean DEFAULT true,
  channel_main boolean DEFAULT true,
  channel_shop boolean DEFAULT true,
  channel_vip boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone DEFAULT now(),
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT push_subscriptions_recruit_id_fkey FOREIGN KEY (recruit_id) REFERENCES public.recruits(id)
);
CREATE TABLE public.recruits (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  email text NOT NULL UNIQUE,
  password text DEFAULT 'password'::text,
  mt5_id text,
  affiliate_code text UNIQUE,
  referred_by_code text,
  social_handle text,
  task_broker_verified boolean DEFAULT false,
  task_social_verified boolean DEFAULT false,
  status text DEFAULT 'Pending'::text,
  commission_balance numeric DEFAULT 0.00,
  total_referred_manual integer,
  used_code boolean DEFAULT false,
  image_url text,
  is_vip boolean DEFAULT false,
  vip_updated_at timestamp with time zone,
  full_name text,
  phone text,
  telegram_username text,
  discord_username text,
  notes text,
  notifications_enabled boolean DEFAULT false,
  notify_trades boolean DEFAULT true,
  notify_livestreams boolean DEFAULT true,
  notify_news boolean DEFAULT true,
  notify_vip boolean DEFAULT true,
  notification_sound boolean DEFAULT true,
  instagram_username text,
  facebook_username text,
  twitter_username text,
  youtube_username text,
  twitch_username text,
  tiktok_username text,
  cell_number text,
  country text,
  city text,
  timezone text,
  birth_date text,
  preferred_contact_method text,
  trading_experience_years integer,
  trading_style text,
  risk_tolerance text,
  preferred_instruments text,
  trading_timezone text,
  account_balance_range text,
  preferred_leverage text,
  favorite_pairs text,
  trading_strategy text,
  win_rate_target numeric,
  monthly_profit_target text,
  hobbies text,
  personality_traits text,
  trading_goals text,
  learning_style text,
  notification_preferences text,
  preferred_chart_timeframe text,
  uses_automated_trading boolean DEFAULT false,
  attends_live_sessions boolean DEFAULT false,
  bio text,
  affiliate_tier text DEFAULT 'Starter'::text,
  affiliate_tier_updated_at timestamp with time zone DEFAULT now(),
  total_earnings numeric DEFAULT 0.00,
  pending_earnings numeric DEFAULT 0.00,
  paid_earnings numeric DEFAULT 0.00,
  last_payout_date timestamp with time zone,
  last_payout_amount numeric,
  total_referred_traders integer DEFAULT 0,
  active_traders integer DEFAULT 0,
  total_lots_traded numeric DEFAULT 0.00,
  monthly_lots_traded numeric DEFAULT 0.00,
  social_posts_this_week integer DEFAULT 0,
  social_posts_this_month integer DEFAULT 0,
  social_bonus_multiplier numeric DEFAULT 1.00,
  last_social_post_date timestamp with time zone,
  preferred_broker text DEFAULT 'Vantage'::text,
  conversion_rate numeric DEFAULT 0.00,
  avg_trader_volume numeric DEFAULT 0.00,
  best_month_earnings numeric DEFAULT 0.00,
  payment_method text,
  payment_details jsonb,
  payment_verified boolean DEFAULT false,
  custom_referral_link text,
  link_clicks integer DEFAULT 0,
  link_last_clicked timestamp with time zone,
  display_name text,
  shipping_addresses jsonb DEFAULT '[]'::jsonb,
  preferred_currency text DEFAULT 'USD'::text,
  preferred_language text DEFAULT 'en'::text,
  store_customer_since timestamp with time zone,
  store_order_count integer DEFAULT 0,
  store_total_spent numeric DEFAULT 0.00,
  store_newsletter_subscribed boolean DEFAULT false,
  rewards_punches integer DEFAULT 0,
  rewards_total_spent numeric DEFAULT 0,
  rewards_cards_completed integer DEFAULT 0,
  rewards_tier text DEFAULT 'bronze'::text CHECK (rewards_tier = ANY (ARRAY['bronze'::text, 'silver'::text, 'gold'::text, 'platinum'::text])),
  rewards_lifetime_points integer DEFAULT 0,
  rewards_available_points integer DEFAULT 0,
  rewards_last_punch_at timestamp with time zone,
  rewards_free_item_claimed boolean DEFAULT false,
  dashboard_preferences jsonb DEFAULT '{"news": {"priority": "all", "autoRefresh": true, "pullInterval": 300000, "soundEnabled": true, "notifications": true, "refreshInterval": 60000}, "quotes": {"category": "all", "autoRefresh": true, "soundEnabled": false, "notifications": false, "refreshInterval": 30000}, "telegram": {"visibility": "all", "autoRefresh": true, "notifyGroups": ["vip"], "soundEnabled": false, "enabledGroups": ["vip", "free", "signals"], "notifications": true, "refreshInterval": 45000}, "watchlist": []}'::jsonb,
  password_hash text,
  CONSTRAINT recruits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  user_id bigint NOT NULL,
  order_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  content text,
  is_verified_purchase boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.recruits(id)
);
CREATE TABLE public.rewards_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recruit_id bigint,
  email text NOT NULL,
  action text NOT NULL,
  punches_change integer DEFAULT 0,
  points_change integer DEFAULT 0,
  order_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by text,
  CONSTRAINT rewards_history_pkey PRIMARY KEY (id),
  CONSTRAINT rewards_history_recruit_id_fkey FOREIGN KEY (recruit_id) REFERENCES public.recruits(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  icon_name character varying,
  price character varying,
  features jsonb DEFAULT '[]'::jsonb,
  cta_text character varying DEFAULT 'Learn More'::character varying,
  cta_url text,
  is_featured boolean DEFAULT false,
  is_visible boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shop_categories (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL UNIQUE,
  CONSTRAINT shop_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shop_hero (
  id boolean NOT NULL DEFAULT true CHECK (id),
  badge text,
  title text,
  subtitle text,
  primary_cta_label text,
  secondary_cta_label text,
  featured_title text,
  featured_subtitle text,
  featured_price_label text,
  featured_tag_label text,
  featured_note text,
  featured_image_url text,
  CONSTRAINT shop_hero_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shop_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  price numeric NOT NULL,
  category character varying,
  image_url text,
  buy_url text,
  visible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shop_products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_name character varying DEFAULT 'BullMoney'::character varying,
  site_tagline character varying DEFAULT 'Elite Trading Community'::character varying,
  meta_description text,
  favicon_url text,
  logo_url text,
  primary_color character varying DEFAULT '#3b82f6'::character varying,
  secondary_color character varying DEFAULT '#f59e0b'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.social_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  platform character varying NOT NULL,
  url text NOT NULL,
  icon_name character varying,
  display_text character varying,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_links_pkey PRIMARY KEY (id)
);
CREATE TABLE public.store_cart (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text NOT NULL,
  item_id text NOT NULL,
  product_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  variant_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  quantity integer NOT NULL DEFAULT 1,
  CONSTRAINT store_cart_pkey PRIMARY KEY (id)
);
CREATE TABLE public.store_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  order_number text NOT NULL UNIQUE,
  email text NOT NULL,
  customer_name text,
  phone text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  subtotal numeric NOT NULL DEFAULT 0,
  shipping_cost numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  discount_code text,
  gift_card_code text,
  gift_card_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  currency text DEFAULT 'USD'::text,
  shipping_address jsonb,
  shipping_method text DEFAULT 'standard'::text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text, 'refunded'::text])),
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'refunded'::text])),
  fulfillment_status text DEFAULT 'unfulfilled'::text CHECK (fulfillment_status = ANY (ARRAY['unfulfilled'::text, 'partial'::text, 'fulfilled'::text])),
  stripe_session_id text,
  stripe_payment_intent text,
  payment_method text,
  tracking_number text,
  tracking_url text,
  carrier text,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  customer_notes text,
  internal_notes text,
  ip_address text,
  user_agent text,
  source text DEFAULT 'web'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT store_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.store_wishlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  email text NOT NULL,
  product_id text NOT NULL,
  product_name text NOT NULL,
  product_slug text NOT NULL,
  product_price numeric NOT NULL DEFAULT 0,
  product_image text,
  CONSTRAINT store_wishlist_pkey PRIMARY KEY (id)
);
CREATE TABLE public.testimonials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author_name character varying NOT NULL,
  author_title character varying,
  author_image_url text,
  content text NOT NULL,
  rating integer DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
  is_featured boolean DEFAULT false,
  is_visible boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT testimonials_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trade_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trade_id uuid NOT NULL,
  user_id text NOT NULL,
  image_url text NOT NULL,
  image_type character varying,
  caption text,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trade_images_pkey PRIMARY KEY (id),
  CONSTRAINT trade_images_trade_id_fkey FOREIGN KEY (trade_id) REFERENCES public.trades(id),
  CONSTRAINT fk_trade FOREIGN KEY (trade_id) REFERENCES public.trades(id)
);
CREATE TABLE public.trades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  asset_symbol character varying NOT NULL,
  asset_name character varying,
  asset_type USER-DEFINED NOT NULL,
  direction USER-DEFINED NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  entry_price numeric NOT NULL CHECK (entry_price > 0::numeric),
  exit_price numeric CHECK (exit_price IS NULL OR exit_price > 0::numeric),
  entry_date timestamp with time zone NOT NULL DEFAULT now(),
  exit_date timestamp with time zone,
  stop_loss numeric,
  take_profit numeric,
  risk_amount numeric,
  risk_percentage numeric,
  commission numeric DEFAULT 0,
  fees numeric DEFAULT 0,
  swap numeric DEFAULT 0,
  gross_pnl numeric,
  net_pnl numeric,
  pnl_percentage numeric,
  outcome USER-DEFINED,
  status USER-DEFINED DEFAULT 'open'::trade_status,
  strategy character varying,
  setup character varying,
  timeframe character varying,
  session USER-DEFINED,
  market_condition character varying,
  news_events text,
  entry_reason text,
  exit_reason text,
  notes text,
  risk_reward_ratio numeric,
  mae numeric,
  mfe numeric,
  account_balance numeric,
  position_size_dollars numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trades_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trading_course_certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  level_id uuid,
  certificate_url text,
  completion_percentage integer NOT NULL,
  issued_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trading_course_certificates_pkey PRIMARY KEY (id),
  CONSTRAINT trading_course_certificates_level_id_fkey FOREIGN KEY (level_id) REFERENCES public.trading_course_levels(id)
);
CREATE TABLE public.trading_course_lessons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module_id uuid,
  title character varying NOT NULL,
  description text,
  content_type character varying NOT NULL,
  video_url text,
  video_thumbnail text,
  article_content text,
  image_urls ARRAY,
  duration_minutes integer,
  order_index integer NOT NULL,
  is_free boolean DEFAULT false,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trading_course_lessons_pkey PRIMARY KEY (id),
  CONSTRAINT trading_course_lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.trading_course_modules(id)
);
CREATE TABLE public.trading_course_levels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  level_name character varying NOT NULL UNIQUE,
  display_name character varying NOT NULL,
  description text,
  icon_url text,
  order_index integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trading_course_levels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trading_course_modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  level_id uuid,
  title character varying NOT NULL,
  description text,
  thumbnail_url text,
  order_index integer NOT NULL,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trading_course_modules_pkey PRIMARY KEY (id),
  CONSTRAINT trading_course_modules_level_id_fkey FOREIGN KEY (level_id) REFERENCES public.trading_course_levels(id)
);
CREATE TABLE public.trading_course_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  lesson_id uuid,
  completed boolean DEFAULT false,
  progress_percentage integer DEFAULT 0,
  time_spent_minutes integer DEFAULT 0,
  last_watched_position integer DEFAULT 0,
  notes text,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trading_course_progress_pkey PRIMARY KEY (id),
  CONSTRAINT trading_course_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.trading_course_lessons(id)
);
CREATE TABLE public.trading_course_quiz_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  quiz_id uuid,
  selected_answer integer NOT NULL,
  is_correct boolean NOT NULL,
  attempted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trading_course_quiz_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT trading_course_quiz_attempts_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.trading_course_quizzes(id)
);
CREATE TABLE public.trading_course_quizzes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_id uuid,
  question text NOT NULL,
  options jsonb NOT NULL,
  correct_answer integer NOT NULL,
  explanation text,
  order_index integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trading_course_quizzes_pkey PRIMARY KEY (id),
  CONSTRAINT trading_course_quizzes_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.trading_course_lessons(id)
);
CREATE TABLE public.trading_course_resources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lesson_id uuid,
  title character varying NOT NULL,
  description text,
  resource_type character varying NOT NULL,
  file_url text NOT NULL,
  file_size_kb integer,
  download_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trading_course_resources_pkey PRIMARY KEY (id),
  CONSTRAINT trading_course_resources_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.trading_course_lessons(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  username text NOT NULL UNIQUE,
  display_name text,
  avatar_url text,
  bio text,
  reputation_score integer DEFAULT 0,
  win_rate numeric,
  total_trades integer DEFAULT 0,
  winning_trades integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  is_smart_money boolean DEFAULT false,
  subscription_tier text DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'pro'::text, 'elite'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_sessions (
  id text NOT NULL,
  started_at timestamp with time zone DEFAULT now(),
  device_info jsonb DEFAULT '{}'::jsonb,
  page_views ARRAY DEFAULT '{}'::text[],
  event_count integer DEFAULT 0,
  error_count integer DEFAULT 0,
  last_activity timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  avg_fps real,
  min_fps integer,
  total_jank_events integer DEFAULT 0,
  memory_peak_mb real,
  crash_predictions jsonb DEFAULT '[]'::jsonb,
  performance_score integer,
  user_journey jsonb,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_trading_stats (
  user_id uuid NOT NULL,
  total_trades integer DEFAULT 0,
  total_wins integer DEFAULT 0,
  total_losses integer DEFAULT 0,
  total_breakeven integer DEFAULT 0,
  total_pnl numeric DEFAULT 0,
  best_trade numeric DEFAULT 0,
  worst_trade numeric DEFAULT 0,
  average_win numeric,
  average_loss numeric,
  average_trade_duration interval,
  overall_win_rate numeric,
  overall_profit_factor numeric,
  longest_win_streak integer DEFAULT 0,
  longest_loss_streak integer DEFAULT 0,
  current_win_streak integer DEFAULT 0,
  current_loss_streak integer DEFAULT 0,
  sharpe_ratio numeric,
  sortino_ratio numeric,
  max_drawdown numeric,
  max_drawdown_amount numeric,
  last_trade_date timestamp with time zone,
  stats_updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_trading_stats_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_trading_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.variants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  sku character varying UNIQUE,
  name character varying NOT NULL,
  options jsonb NOT NULL DEFAULT '{}'::jsonb,
  price_adjustment numeric DEFAULT 0,
  inventory_count integer NOT NULL DEFAULT 0 CHECK (inventory_count >= 0),
  low_stock_threshold integer DEFAULT 5,
  weight_grams integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT variants_pkey PRIMARY KEY (id),
  CONSTRAINT variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.vip_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message text NOT NULL,
  has_media boolean DEFAULT false,
  views integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  telegram_message_id integer,
  notification_sent boolean DEFAULT false,
  chat_id text,
  chat_title text,
  media_url text,
  media_type text,
  CONSTRAINT vip_messages_pkey PRIMARY KEY (id)
);